=== MITLibraries/geo-harvester/harvester/records/schemas/geoblacklight-schema-aardvark.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "GeoBlacklight Schema - Aardvark",
    "description": "Schema for GeoBlacklight. See https://opengeometadata.github.io/aardvark/aardvarkMetadata.html for more details.",
    "type": "object",
    "properties": {
        "dct_title_s": {
            "$anchor": "dc_title_s",
            "type": "string"
        },
        "dct_alternative_sm": {
            "$anchor": "dct_alternative_sm",
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "dct_description_sm": {
            "$anchor": "dct_description_sm",
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "dct_language_sm": {
            "$anchor": "dct_language_sm",
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "gbl_displayNote_sm": {
            "$anchor": "gbl_displayNote_sm",
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "dct_creator_sm": {
            "$anchor": "dct_creator_sm",
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "dct_publisher_sm": {
            "$anchor": "dct_publisher_sm",
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "schema_provider_s": {
            "$anchor": "schema_provider_s",
            "type": "string"
        },
        "gbl_resourceClass_sm": {
            "$anchor": "gbl_resourceClass_sm",
            "type": "array",
            "items": {
                "type": "string",
                "enum": [
                    "Datasets",
                    "Maps",
                    "Imagery",
                    "Collections",
                    "Websites",
                    "Web services",
                    "Other"
                ]
            }
        },
        "gbl_resourceType_sm": {
            "$anchor": "gbl_resourceType_sm",
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "dct_subject_sm": {
            "$anchor": "dct_subject_sm",
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "dcat_theme_sm": {
            "$anchor": "dcat_theme_sm",
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "dcat_keyword_sm": {
            "$anchor": "dcat_keyword_sm",
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "dct_temporal_sm": {
            "$anchor": "dct_temporal_sm",
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "dct_issued_s": {
            "$anchor": "dct_issued_s",
            "type": "string"
        },
        "gbl_indexYear_im": {
            "$anchor": "gbl_indexYear_im",
            "type": "array",
            "items": {
                "type": "integer"
            }
        },
        "gbl_dateRange_drsim": {
            "$anchor": "gbl_dateRange_drsim",
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "dct_spatial_sm": {
            "$anchor": "dct_spatial_sm",
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "locn_geometry": {
            "$anchor": "locn_geometry",
            "type": "string"
        },
        "dcat_bbox": {
            "$anchor": "dcat_bbox",
            "type": "string"
        },
        "dcat_centroid": {
            "$anchor": "dcat_centroid",
            "type": "string"
        },
        "dct_relation_sm": {
            "$anchor": "dct_relation_sm",
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "pcdm_memberOf_sm": {
            "$anchor": "pcdm_memberOf_sm",
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "dct_isPartOf_sm": {
            "$anchor": "dct_isPartOf_sm",
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "dct_source_sm": {
            "$anchor": "dct_source_sm",
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "dct_isVersionOf_sm": {
            "$anchor": "dct_isVersionOf_sm",
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "dct_replaces_sm": {
            "$anchor": "dct_replaces_sm",
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "dct_isReplacedBy_sm": {
            "$anchor": "dct_isReplacedBy_sm",
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "dct_rights_sm": {
            "$anchor": "dct_rights_sm",
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "dct_rightsHolder_sm": {
            "$anchor": "dct_rightsHolder_sm",
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "dct_license_sm": {
            "$anchor": "dct_license_sm",
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "dct_accessRights_s": {
            "$anchor": "dct_accessRights_s",
            "type": "string"
        },
        "dct_format_s": {
            "$anchor": "dct_format_s",
            "type": "string"
        },
        "gbl_fileSize_s": {
            "$anchor": "gbl_fileSize_s",
            "type": "string"
        },
        "gbl_wxsIdentifier_s": {
            "$anchor": "gbl_wxsIdentifier_s",
            "type": "string"
        },
        "dct_references_s": {
            "$anchor": "dct_references_s",
            "type": "string"
        },
        "id": {
            "$anchor": "id",
            "type": "string"
        },
        "dct_identifier_sm": {
            "$anchor": "dct_identifier_sm",
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "gbl_mdModified_dt": {
            "$anchor": "gbl_mdModified_dt",
            "type": "string",
            "format": "date-time"
        },
        "gbl_mdVersion_s": {
            "$anchor": "gbl_mdVersion_s",
            "type": "string",
            "const": "Aardvark"
        },
        "gbl_suppressed_b": {
            "$anchor": "gbl_suppressed_b",
            "type": "boolean"
        },
        "gbl_georeferenced_b": {
            "$anchor": "gbl_georeferenced_b",
            "type": "boolean"
        }
    },
    "required": [
        "id",
        "dct_title_s",
        "gbl_resourceClass_sm",
        "dct_accessRights_s",
        "gbl_mdVersion_s"
    ]
}

=== MITLibraries/geo-harvester/tests/fixtures/records/aardvark/aardvark_all_fields.json
{
  "dct_accessRights_s": "Restricted",
  "dct_title_s": "Egypt, Cairo (Topographic Map, 1972)",
  "gbl_mdModified_dt": "2024-02-08T21:28:41+00:00",
  "gbl_mdVersion_s": "Aardvark",
  "gbl_resourceClass_sm": [
    "Imagery"
  ],
  "id": "mit:EG_CAIRO_A25TOPO_1972",
  "dcat_bbox": "ENVELOPE(31.161907, 31.381609, 30.141311, 29.994131)",
  "dct_references_s": "{\"http://schema.org/downloadUrl\": [{\"label\": \"Source Metadata\", \"url\": \"https://cdn.dev1.mitlibrary.net/geo/public/EG_CAIRO_A25TOPO_1972.source.fgdc.xml\"}, {\"label\": \"Aardvark Metadata\", \"url\": \"https://cdn.dev1.mitlibrary.net/geo/public/EG_CAIRO_A25TOPO_1972.normalized.aardvark.json\"}, {\"label\": \"Data\", \"url\": \"https://cdn.dev1.mitlibrary.net/geo/restricted/EG_CAIRO_A25TOPO_1972.zip\"}], \"http://schema.org/url\": \"https://geodata.libraries.mit.edu/record/gismit:EG_CAIRO_A25TOPO_1972\"}",
  "locn_geometry": "ENVELOPE(31.161907, 31.381609, 30.141311, 29.994131)",
  "dcat_theme_sm": [
    "Elevation"
  ],
  "dct_creator_sm": [
    "Soviet Union. Sovetskaia Armiia. Generalnyi Shtab (Soviet)"
  ],
  "dct_description_sm": [
    "This layer is a georeferenced raster image of a paper map entitled Cairo (H-36-63, 75). The original scanned image with the legend and other information regarding the source is available in Dome. See the online linkage."
  ],
  "dct_format_s": "Raster",
  "dct_identifier_sm": [
    "EG_CAIRO_A25TOPO_1972",
    "http://hdl.handle.net/1721.3/172443",
    "EG_CAIRO_A25TOPO_1972.tif"
  ],
  "dct_issued_s": "1972-01-01",
  "dct_language_sm": [
    "eng"
  ],
  "dct_publisher_sm": [
    "LAND INFO Worldwide Mapping, LLC"
  ],
  "dct_rights_sm": [
    "All data is the copyrighted property of LAND INFO Worldwide Mapping, LLC and/or its suppliers. Land Info grants customer unlimited, perpetual license for academic use of data and license to distribute data on a non-commercial basis, or as Derived Works. Derived works that include the source data must be merged with other value-added data in such a way that the derived work can\u2019t be converted back to the original source data format. Other Derived Works that don\u2019t include the source data (vector extraction, classification etc.) have no restrictions on use and distribution. An unlimited license is granted for media use, provided that the following citation is used: \"map data courtesy www.landinfo.com.\""
  ],
  "dct_spatial_sm": [
    "Egypt",
    "Cairo"
  ],
  "dct_subject_sm": [
    "maps",
    "topographic maps",
    "raster",
    "land use",
    "imageryBaseMapsEarthCover",
    "elevation"
  ],
  "dct_temporal_sm": [
    "1972-01-01"
  ],
  "gbl_indexYear_im": [
    1972
  ],
  "gbl_suppressed_b": false,
  "schema_provider_s": "GIS Lab, MIT Libraries",
  "dcat_keyword_sm": ["fish","snails"],
  "dct_alternative_sm": ["This is another title"],
  "gbl_dateRange_drsim": ["[1990 TO 1991]"],
  "gbl_resourceType_sm": ["Raster data"]
}
